# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.xslt_transform <- function(xslt_doc, xml_doc, process_includes = FALSE, load_external_subsets = FALSE, validate_xml = FALSE) {
    .Call('xslt_xslt_transform', PACKAGE = 'xslt', xslt_doc, xml_doc, process_includes, load_external_subsets, validate_xml)
}

